In [6]:
import numpy as np
import pandas as pd

import warnings

warnings.filterwarnings('ignore')

In [7]:
df = pd.read_csv('train_EDA.csv')
df.head()

,vendor_id,passenger_count,pickup_longitude,pickup_latitude,dropoff_longitude,dropoff_latitude,store_and_fwd_flag,trip_duration,pickup_month,pickup_dayofweek,pickup_slot,dropoff_month,dropoff_dayofweek,dropoff_hour,dropoff_slot
0,1,1,-73.982155,40.767937,-73.964630,40.765602,N,455,3,0,Evening,3,0,17,Evening
1,0,1,-73.980415,40.738564,-73.999481,40.731152,N,663,6,6,Late_Night,6,6,0,Late_Night
2,1,1,-74.010040,40.719971,-74.012268,40.706718,N,429,4,2,Night,4,2,19,Night
3,1,1,-73.973053,40.793209,-73.972923,40.782520,N,435,3,5,Noon,3,5,13,Noon
4,1,6,-73.982857,40.742195,-73.992081,40.749184,N,443,1,5,Midnight,1,5,22,Midnight

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1066333 entries, 0 to 1066332
Data columns (total 15 columns):
 #   Column              Non-Null Count    Dtype
---  ------              --------------    -----
 0   vendor_id           1066333 non-null  int64
 1   passenger_count     1066333 non-null  int64
 2   pickup_longitude    1066333 non-null  float64
 3   pickup_latitude     1066333 non-null  float64
 4   dropoff_longitude   1066333 non-null  float64
 5   dropoff_latitude    1066333 non-null  float64
 6   store_and_fwd_flag  1066333 non-null  object
 7   trip_duration       1066333 non-null  int64
 8   pickup_month        1066333 non-null  int64
 9   pickup_dayofweek    1066333 non-null  int64
 10  pickup_slot         1066333 non-null  object
 11  dropoff_month       1066333 non-null  int64
 12  dropoff_dayofweek   1066333 non-null  int64
 13  dropoff_hour        1066333 non-null  int64
 14  dropoff_slot        1066333 non-null  object
dtypes: float64(4), int64(8), object(3)
memory usage: 122.0+ MB

In [24]:
df['store_and_fwd_flag'] = df['store_and_fwd_flag'].map({'Y':1, 'N':0})
df.head()

,vendor_id,passenger_count,pickup_longitude,pickup_latitude,dropoff_longitude,dropoff_latitude,store_and_fwd_flag,trip_duration,pickup_month_2,pickup_month_3,...,dropoff_dayofweek_3,dropoff_dayofweek_4,dropoff_dayofweek_5,dropoff_dayofweek_6,dropoff_slot_Evening,dropoff_slot_Late_Night,dropoff_slot_Midnight,dropoff_slot_Morning,dropoff_slot_Night,dropoff_slot_Noon
0,1,1,-73.982155,40.767937,-73.964630,40.765602,NaN,455,0,1,...,0,0,0,0,1,0,0,0,0,0
1,0,1,-73.980415,40.738564,-73.999481,40.731152,NaN,663,0,0,...,0,0,0,1,0,1,0,0,0,0
2,1,1,-74.010040,40.719971,-74.012268,40.706718,NaN,429,0,0,...,0,0,0,0,0,0,0,0,1,0
3,1,1,-73.973053,40.793209,-73.972923,40.782520,NaN,435,0,1,...,0,0,1,0,0,0,0,0,0,1
4,1,6,-73.982857,40.742195,-73.992081,40.749184,NaN,443,0,0,...,0,0,1,0,0,0,1,0,0,0

In [25]:
d_pickup_month = pd.get_dummies(df['pickup_month'], prefix='pickup_month', drop_first=True)
d_pickup_month.head()

KeyError: 'pickup_month'

In [ ]:
df = pd.concat([df, d_pickup_month], axis=1)
df = df.drop('pickup_month', axis=1)
df.head()

,vendor_id,passenger_count,pickup_longitude,pickup_latitude,dropoff_longitude,dropoff_latitude,store_and_fwd_flag,trip_duration,pickup_dayofweek,pickup_slot,dropoff_month,dropoff_dayofweek,dropoff_hour,dropoff_slot,pickup_month_2,pickup_month_3,pickup_month_4,pickup_month_5,pickup_month_6
0,1,1,-73.982155,40.767937,-73.964630,40.765602,0,455,0,Evening,3,0,17,Evening,0,1,0,0,0
1,0,1,-73.980415,40.738564,-73.999481,40.731152,0,663,6,Late_Night,6,6,0,Late_Night,0,0,0,0,1
2,1,1,-74.010040,40.719971,-74.012268,40.706718,0,429,2,Night,4,2,19,Night,0,0,1,0,0
3,1,1,-73.973053,40.793209,-73.972923,40.782520,0,435,5,Noon,3,5,13,Noon,0,1,0,0,0
4,1,6,-73.982857,40.742195,-73.992081,40.749184,0,443,5,Midnight,1,5,22,Midnight,0,0,0,0,0

In [ ]:
d_pickup_dayofweek = pd.get_dummies(df['pickup_dayofweek'], prefix='pickup_dayofweek', drop_first=True)
d_pickup_dayofweek.head()

,pickup_dayofweek_1,pickup_dayofweek_2,pickup_dayofweek_3,pickup_dayofweek_4,pickup_dayofweek_5,pickup_dayofweek_6
0,0,0,0,0,0,0
1,0,0,0,0,0,1
2,0,1,0,0,0,0
3,0,0,0,0,1,0
4,0,0,0,0,1,0

In [ ]:
df = pd.concat([df, d_pickup_dayofweek], axis=1)
df = df.drop('pickup_dayofweek', axis=1)
df.head()

,vendor_id,passenger_count,pickup_longitude,pickup_latitude,dropoff_longitude,dropoff_latitude,store_and_fwd_flag,trip_duration,pickup_slot,dropoff_month,...,pickup_month_3,pickup_month_4,pickup_month_5,pickup_month_6,pickup_dayofweek_1,pickup_dayofweek_2,pickup_dayofweek_3,pickup_dayofweek_4,pickup_dayofweek_5,pickup_dayofweek_6
0,1,1,-73.982155,40.767937,-73.964630,40.765602,0,455,Evening,3,...,1,0,0,0,0,0,0,0,0,0
1,0,1,-73.980415,40.738564,-73.999481,40.731152,0,663,Late_Night,6,...,0,0,0,1,0,0,0,0,0,1
2,1,1,-74.010040,40.719971,-74.012268,40.706718,0,429,Night,4,...,0,1,0,0,0,1,0,0,0,0
3,1,1,-73.973053,40.793209,-73.972923,40.782520,0,435,Noon,3,...,1,0,0,0,0,0,0,0,1,0
4,1,6,-73.982857,40.742195,-73.992081,40.749184,0,443,Midnight,1,...,0,0,0,0,0,0,0,0,1,0

In [ ]:
d_pickup_slot = pd.get_dummies(df['pickup_slot'], prefix='pickup_slot', drop_first=True)
d_pickup_slot.head()

,pickup_slot_Evening,pickup_slot_Late_Night,pickup_slot_Midnight,pickup_slot_Morning,pickup_slot_Night,pickup_slot_Noon
0,1,0,0,0,0,0
1,0,1,0,0,0,0
2,0,0,0,0,1,0
3,0,0,0,0,0,1
4,0,0,1,0,0,0

In [ ]:
df = pd.concat([df, d_pickup_slot], axis=1)
df = df.drop('pickup_slot', axis=1)
df.head()

,vendor_id,passenger_count,pickup_longitude,pickup_latitude,dropoff_longitude,dropoff_latitude,store_and_fwd_flag,trip_duration,dropoff_month,dropoff_dayofweek,...,pickup_dayofweek_3,pickup_dayofweek_4,pickup_dayofweek_5,pickup_dayofweek_6,pickup_slot_Evening,pickup_slot_Late_Night,pickup_slot_Midnight,pickup_slot_Morning,pickup_slot_Night,pickup_slot_Noon
0,1,1,-73.982155,40.767937,-73.964630,40.765602,0,455,3,0,...,0,0,0,0,1,0,0,0,0,0
1,0,1,-73.980415,40.738564,-73.999481,40.731152,0,663,6,6,...,0,0,0,1,0,1,0,0,0,0
2,1,1,-74.010040,40.719971,-74.012268,40.706718,0,429,4,2,...,0,0,0,0,0,0,0,0,1,0
3,1,1,-73.973053,40.793209,-73.972923,40.782520,0,435,3,5,...,0,0,1,0,0,0,0,0,0,1
4,1,6,-73.982857,40.742195,-73.992081,40.749184,0,443,1,5,...,0,0,1,0,0,0,1,0,0,0

In [ ]:
d_dropoff_month = pd.get_dummies(df['dropoff_month'], prefix='dropoff_month', drop_first=True)
d_dropoff_month.head()

,dropoff_month_2,dropoff_month_3,dropoff_month_4,dropoff_month_5,dropoff_month_6,dropoff_month_7
0,0,1,0,0,0,0
1,0,0,0,0,1,0
2,0,0,1,0,0,0
3,0,1,0,0,0,0
4,0,0,0,0,0,0

In [ ]:
df = pd.concat([df, d_dropoff_month], axis=1)
df = df.drop('dropoff_month', axis=1)
df.head()

,vendor_id,passenger_count,pickup_longitude,pickup_latitude,dropoff_longitude,dropoff_latitude,store_and_fwd_flag,trip_duration,dropoff_dayofweek,dropoff_hour,...,pickup_slot_Midnight,pickup_slot_Morning,pickup_slot_Night,pickup_slot_Noon,dropoff_month_2,dropoff_month_3,dropoff_month_4,dropoff_month_5,dropoff_month_6,dropoff_month_7
0,1,1,-73.982155,40.767937,-73.964630,40.765602,0,455,0,17,...,0,0,0,0,0,1,0,0,0,0
1,0,1,-73.980415,40.738564,-73.999481,40.731152,0,663,6,0,...,0,0,0,0,0,0,0,0,1,0
2,1,1,-74.010040,40.719971,-74.012268,40.706718,0,429,2,19,...,0,0,1,0,0,0,1,0,0,0
3,1,1,-73.973053,40.793209,-73.972923,40.782520,0,435,5,13,...,0,0,0,1,0,1,0,0,0,0
4,1,6,-73.982857,40.742195,-73.992081,40.749184,0,443,5,22,...,1,0,0,0,0,0,0,0,0,0

In [ ]:
d_dropoff_dayofweek = pd.get_dummies(df['dropoff_dayofweek'], prefix='dropoff_dayofweek', drop_first=True)
d_dropoff_dayofweek.head()

,dropoff_dayofweek_1,dropoff_dayofweek_2,dropoff_dayofweek_3,dropoff_dayofweek_4,dropoff_dayofweek_5,dropoff_dayofweek_6
0,0,0,0,0,0,0
1,0,0,0,0,0,1
2,0,1,0,0,0,0
3,0,0,0,0,1,0
4,0,0,0,0,1,0

In [ ]:
df = pd.concat([df, d_dropoff_dayofweek], axis=1)
df = df.drop('dropoff_dayofweek', axis=1)
df.head()

,vendor_id,passenger_count,pickup_longitude,pickup_latitude,dropoff_longitude,dropoff_latitude,store_and_fwd_flag,trip_duration,dropoff_hour,dropoff_slot,...,dropoff_month_4,dropoff_month_5,dropoff_month_6,dropoff_month_7,dropoff_dayofweek_1,dropoff_dayofweek_2,dropoff_dayofweek_3,dropoff_dayofweek_4,dropoff_dayofweek_5,dropoff_dayofweek_6
0,1,1,-73.982155,40.767937,-73.964630,40.765602,0,455,17,Evening,...,0,0,0,0,0,0,0,0,0,0
1,0,1,-73.980415,40.738564,-73.999481,40.731152,0,663,0,Late_Night,...,0,0,1,0,0,0,0,0,0,1
2,1,1,-74.010040,40.719971,-74.012268,40.706718,0,429,19,Night,...,1,0,0,0,0,1,0,0,0,0
3,1,1,-73.973053,40.793209,-73.972923,40.782520,0,435,13,Noon,...,0,0,0,0,0,0,0,0,1,0
4,1,6,-73.982857,40.742195,-73.992081,40.749184,0,443,22,Midnight,...,0,0,0,0,0,0,0,0,1,0

In [ ]:
d_dropoff_slot = pd.get_dummies(df['dropoff_slot'], prefix='dropoff_slot', drop_first=True)
d_dropoff_slot.head()

,dropoff_slot_Evening,dropoff_slot_Late_Night,dropoff_slot_Midnight,dropoff_slot_Morning,dropoff_slot_Night,dropoff_slot_Noon
0,1,0,0,0,0,0
1,0,1,0,0,0,0
2,0,0,0,0,1,0
3,0,0,0,0,0,1
4,0,0,1,0,0,0

In [ ]:
df = pd.concat([df, d_dropoff_slot], axis=1)
df = df.drop('dropoff_slot', axis=1)
df.head()

,vendor_id,passenger_count,pickup_longitude,pickup_latitude,dropoff_longitude,dropoff_latitude,store_and_fwd_flag,trip_duration,dropoff_hour,pickup_month_2,...,dropoff_dayofweek_3,dropoff_dayofweek_4,dropoff_dayofweek_5,dropoff_dayofweek_6,dropoff_slot_Evening,dropoff_slot_Late_Night,dropoff_slot_Midnight,dropoff_slot_Morning,dropoff_slot_Night,dropoff_slot_Noon
0,1,1,-73.982155,40.767937,-73.964630,40.765602,0,455,17,0,...,0,0,0,0,1,0,0,0,0,0
1,0,1,-73.980415,40.738564,-73.999481,40.731152,0,663,0,0,...,0,0,0,1,0,1,0,0,0,0
2,1,1,-74.010040,40.719971,-74.012268,40.706718,0,429,19,0,...,0,0,0,0,0,0,0,0,1,0
3,1,1,-73.973053,40.793209,-73.972923,40.782520,0,435,13,0,...,0,0,1,0,0,0,0,0,0,1
4,1,6,-73.982857,40.742195,-73.992081,40.749184,0,443,22,0,...,0,0,1,0,0,0,1,0,0,0

In [ ]:
df.corr()

,vendor_id,passenger_count,pickup_longitude,pickup_latitude,dropoff_longitude,dropoff_latitude,store_and_fwd_flag,trip_duration,dropoff_hour,pickup_month_2,...,dropoff_dayofweek_3,dropoff_dayofweek_4,dropoff_dayofweek_5,dropoff_dayofweek_6,dropoff_slot_Evening,dropoff_slot_Late_Night,dropoff_slot_Midnight,dropoff_slot_Morning,dropoff_slot_Night,dropoff_slot_Noon
vendor_id,1.000000,0.294440,0.008223,0.007936,0.004944,0.006865,-0.072469,0.000857,0.010581,0.003670,...,-0.002008,-0.000568,0.000688,0.003417,0.003282,-0.007305,0.004576,0.005653,0.006577,-0.005287
passenger_count,0.294440,1.000000,-0.002686,-0.003527,-0.002321,-0.001482,-0.021212,0.008638,0.009170,-0.000308,...,-0.008863,-0.000990,0.021189,0.017521,0.000787,0.011537,0.010356,-0.010309,0.004666,0.002211
pickup_longitude,0.008223,-0.002686,1.000000,0.147689,0.779473,0.096096,0.002006,-0.014507,-0.009144,-0.002217,...,0.000968,0.002442,-0.014894,-0.006430,0.007341,-0.030112,-0.017540,0.021900,-0.019730,0.013040
pickup_latitude,0.007936,-0.003527,0.147689,1.000000,0.103666,0.763546,-0.000619,-0.073000,0.032600,-0.001487,...,0.010711,0.004591,-0.028866,-0.026268,0.040926,-0.118172,-0.047361,0.045893,-0.016091,0.052089
dropoff_longitude,0.004944,-0.002321,0.779473,0.103666,1.000000,0.160946,0.001780,0.020319,-0.028804,-0.003415,...,-0.001125,0.001955,-0.013413,0.001792,-0.005033,0.031284,-0.000579,-0.013120,-0.015861,-0.008753
dropoff_latitude,0.006865,-0.001482,0.096096,0.763546,0.160946,1.000000,-0.000788,-0.062111,0.025956,-0.003457,...,0.008069,0.001998,-0.024712,-0.016777,0.033619,-0.077621,-0.031460,0.021075,-0.008871,0.035593
store_and_fwd_flag,-0.072469,-0.021212,0.002006,-0.000619,0.001780,-0.000788,1.000000,0.004686,0.001951,0.000821,...,0.001574,0.000318,-0.000439,-0.002224,0.003725,-0.000937,-0.000844,-0.000430,-0.001252,0.002348
trip_duration,0.000857,0.008638,-0.014507,-0.073000,0.020319,-0.062111,0.004686,1.000000,0.032774,-0.010454,...,0.017694,0.010867,-0.004502,-0.029603,0.005360,-0.006919,0.013776,0.005586,0.005787,0.026282
dropoff_hour,0.010581,0.009170,-0.009144,0.032600,-0.028804,0.025956,0.001951,0.032774,1.000000,0.005933,...,0.027159,-0.001104,-0.038209,-0.089342,0.228598,-0.674970,0.469716,-0.291780,0.468877,-0.004330
pickup_month_2,0.003670,-0.000308,-0.002217,-0.001487,-0.003415,-0.003457,0.000821,-0.010454,0.005933,1.000000,...,-0.003364,-0.005261,-0.000849,-0.002940,0.008326,-0.009708,-0.002901,0.002824,-0.003269,0.007529
pickup_month_3,0.000789,-0.001338,-0.005131,-0.001863,-0.003403,-0.000383,-0.000863,-0.001735,0.007680,-0.209470,...,0.020379,-0.017419,-0.011794,-0.017015,0.005079,-0.010511,-0.002554,-0.000196,0.005085,0.000579
pickup_month_4,-0.002456,0.001807,-0.000894,-0.000934,0.000770,0.001129,0.000131,0.006375,0.000168,-0.204112,...,-0.018128,0.023770,0.038975,-0.006944,-0.003929,0.004425,0.003928,-0.000775,0.003671,-0.005759
pickup_month_5,-0.002490,-0.000761,0.001922,0.001943,0.003153,0.003705,-0.002496,0.007003,-0.005497,-0.200112,...,-0.018765,-0.021605,-0.015091,0.031169,-0.005211,0.006328,0.000906,-0.001335,-0.001359,-0.001607
pickup_month_6,-0.003538,-0.002671,0.002051,0.001993,0.001990,0.000274,0.000781,0.011978,-0.008150,-0.192767,...,0.029086,-0.014576,-0.010732,-0.014328,-0.015006,0.008324,0.008738,0.003557,-0.000262,-0.009168
pickup_dayofweek_1,-0.000200,-0.010413,0.003686,0.014881,0.001774,0.012249,0.000068,0.008934,0.038835,-0.011339,...,-0.162832,-0.167508,-0.172024,-0.161914,0.007418,-0.070508,0.002530,0.014958,0.020095,-0.005311
pickup_dayofweek_2,-0.000706,-0.009548,0.003748,0.013528,0.001515,0.010986,0.000119,0.013397,0.030256,-0.007199,...,-0.157500,-0.169351,-0.173917,-0.163696,-0.006605,-0.056646,0.009121,0.016022,0.020430,-0.010225
pickup_dayofweek_3,-0.001958,-0.008816,0.000652,0.010341,-0.001293,0.007805,0.001230,0.018310,0.025170,-0.003316,...,0.991596,-0.162240,-0.176438,-0.166068,-0.011830,-0.044497,0.017441,0.011415,0.015285,-0.011337
pickup_dayofweek_4,-0.000529,-0.000812,0.002562,0.004386,0.001879,0.001790,0.000441,0.011272,-0.002087,-0.005248,...,-0.171687,0.989955,-0.170864,-0.170719,-0.012062,0.002600,0.016511,-0.000221,0.001041,-0.014245
pickup_dayofweek_5,0.000768,0.021174,-0.015212,-0.028836,-0.013609,-0.024586,-0.000368,-0.004463,-0.038382,-0.000742,...,-0.176220,-0.181279,0.989557,-0.164207,-0.001693,0.093993,0.007616,-0.026758,-0.029703,0.012914
pickup_dayofweek_6,0.003181,0.017322,-0.005431,-0.025439,0.002513,-0.016360,-0.002309,-0.031139,-0.084656,-0.003019,...,-0.165281,-0.170027,-0.174612,0.991875,0.003863,0.133293,-0.040605,-0.025282,-0.040563,0.022472
pickup_slot_Evening,0.003941,0.000745,0.006224,0.038629,-0.005394,0.031317,0.003321,0.010023,0.243168,0.008211,...,-0.010695,-0.010741,-0.003048,-0.000021,0.933065,-0.154982,-0.146862,-0.199834,-0.129804,-0.205105
pickup_slot_Late_Night,-0.008100,0.011353,-0.030435,-0.115663,0.032654,-0.075539,-0.001127,-0.015468,-0.649982,-0.009606,...,-0.047862,-0.000278,0.093416,0.139560,-0.148783,0.961527,-0.122253,-0.166349,-0.169360,-0.170737
pickup_slot_Midnight,0.004436,0.010116,-0.015794,-0.050072,0.000635,-0.033864,-0.000208,0.009655,0.389516,-0.002649,...,0.014939,0.018823,0.011321,-0.033737,-0.142860,-0.055295,0.914220,-0.159727,-0.162618,-0.163940
pickup_slot_Morning,0.006284,-0.009354,0.020010,0.044780,-0.015216,0.019876,-0.000092,0.008666,-0.281157,0.003413,...,0.009127,-0.002041,-0.021480,-0.020493,-0.197707,-0.171435,-0.162452,0.952313,-0.225050,-0.177462
pickup_slot_Night,0.006360,0.005138,-0.020204,-0.019100,-0.014755,-0.010261,-0.001563,0.004735,0.478952,-0.003986,...,0.017412,0.000839,-0.029702,-0.042988,-0.200176,-0.173577,-0.085783,-0.223810,0.934660,-0.229714
pickup_slot_Noon,-0.006067,0.002443,0.012587,0.052465,-0.008379,0.036876,0.002549,0.024718,0.006810,0.007931,...,-0.011095,-0.014186,0.012903,0.021192,-0.152460,-0.175206,-0.166025,-0.225910,-0.229999,0.952994
dropoff_month_2,0.003658,-0.000326,-0.002194,-0.001478,-0.003398,-0.003456,0.000785,-0.010442,0.005969,0.999876,...,-0.003357,-0.005254,-0.000841,-0.002933,0.008334,-0.009757,-0.002895,0.002832,-0.003260,0.007537
dropoff_month_3,0.000808,-0.001350,-0.005107,-0.001854,-0.003395,-0.000376,-0.000823,-0.001770,0.007792,-0.209311,...,0.020402,-0.017699,-0.011771,-0.016994,0.005102,-0.010660,-0.002536,-0.000171,0.005111,0.000605
dropoff_month_4,-0.002442,0.001841,-0.000938,-0.000939,0.000751,0.001126,0.000132,0.006356,0.000204,-0.204107,...,-0.018121,0.024085,0.038984,-0.007302,-0.003922,0.004377,0.003934,-0.000767,0.003680,-0.005751
dropoff_month_5,-0.002525,-0.000780,0.001916,0.001950,0.003148,0.003715,-0.002501,0.007026,-0.005654,-0.200133,...,-0.018794,-0.021636,-0.015122,0.031505,-0.005242,0.006536,0.000880,-0.001371,-0.001395,-0.001644
dropoff_month_6,-0.003477,-0.002642,0.002064,0.002005,0.002025,0.000303,0.000785,0.011980,-0.008022,-0.192751,...,0.029113,-0.014878,-0.010706,-0.014304,-0.014981,0.008154,0.008760,0.003587,-0.000232,-0.009139
dropoff_month_7,-0.002324,-0.001719,0.000041,-0.002414,-0.001551,-0.003102,-0.000440,0.002386,-0.013455,-0.002925,...,-0.002653,0.015463,-0.002803,-0.002638,-0.002728,0.017839,-0.002242,-0.003050,-0.003106,-0.003131
dropoff_dayofweek_1,-0.000343,-0.010472,0.003909,0.015006,0.001660,0.012081,0.000089,0.008856,0.039491,-0.011072,...,-0.162759,-0.167432,-0.171947,-0.161841,0.007551,-0.071385,0.002639,0.015109,0.020250,-0.005163
dropoff_dayofweek_2,-0.000549,-0.009568,0.003746,0.013610,0.001637,0.011059,-0.000052,0.013172,0.031161,-0.007239,...,-0.164522,-0.169246,-0.173809,-0.163594,-0.006427,-0.057853,0.009274,0.016231,0.020645,-0.010023
dropoff_dayofweek_3,-0.002008,-0.008863,0.000968,0.010711,-0.001125,0.008069,0.001574,0.017694,0.027159,-0.003364,...,1.000000,-0.171573,-0.176199,-0.165844,-0.011443,-0.047145,0.017785,0.011872,0.015753,-0.010891
dropoff_dayofweek_4,-0.000568,-0.000990,0.002442,0.004591,0.001955,0.001998,0.000318,0.010867,-0.001104,-0.005261,...,-0.171573,1.000000,-0.181258,-0.170606,-0.011868,0.001296,0.016683,0.000002,0.001269,-0.014022
dropoff_dayofweek_5,0.000688,0.021189,-0.014894,-0.028866,-0.013413,-0.024712,-0.000439,-0.004502,-0.038209,-0.000849,...,-0.176199,-0.181258,1.000000,-0.175206,-0.001657,0.093767,0.007646,-0.026720,-0.029664,0.012956
dropoff_dayofweek_6,0.003417,0.017521,-0.006430,-0.026268,0.001792,-0.016777,-0.002224,-0.029603,-0.089342,-0.002940,...,-0.165844,-0.170606,-0.175206,1.000000,0.002862,0.139454,-0.041321,-0.026330,-0.041593,0.021279
dropoff_slot_Evening,0.003282,0.000787,0.007341,0.040926,-0.005033,0.033619,0.003725,0.005360,0.228598,0.008326,...,-0.011443,-0.011868,-0.001657,0.002862,1.000000,-0.152943,-0.144929,-0.197204,-0.200774,-0.202406
dropoff_slot_Late_Night,-0.007305,0.011537,-0.030112,-0.118172,0.031284,-0.077621,-0.000937,-0.006919,-0.674970,-0.009708,...,-0.047145,0.001296,0.093767,0.139454,-0.152943,1.000000,-0.125671,-0.171000,-0.174095,-0.175510
dropoff_slot_Midnight,0.004576,0.010356,-0.017540,-0.047361,-0.000579,-0.031460,-0.000844,0.013776,0.469716,-0.002901,...,0.017785,0.016683,0.007646,-0.041321,-0.144929,-0.125671,1.000000,-0.162039,-0.164973,-0.166314
dropoff_slot_Morning,0.005653,-0.010309,0.021900,0.045893,-0.013120,0.021075,-0.000430,0.005586,-0.291780,0.002824,...,0.011872,0.000002,-0.026720,-0.026330,-0.197204,-0.171000,-0.162039,1.000000,-0.224478,-0.226303
dropoff_slot_Night,0.006577,0.004666,-0.019730,-0.016091,-0.015861,-0.008871,-0.001252,0.005787,0.468877,-0.003269,...,0.015753,0.001269,-0.029664,-0.041593,-0.200774,-0.174095,-0.164973,-0.224478,1.000000,-0.230399
dropoff_slot_Noon,-0.005287,0.002211,0.013040,0.052089,-0.008753,0.035593,0.002348,0.026282,-0.004330,0.007529,...,-0.010891,-0.014022,0.012956,0.021279,-0.202406,-0.175510,-0.166314,-0.226303,-0.230399,1.000000

In [ ]:
df = df.drop('dropoff_hour', axis=1)

In [26]:
df.head()

,vendor_id,passenger_count,pickup_longitude,pickup_latitude,dropoff_longitude,dropoff_latitude,store_and_fwd_flag,trip_duration,pickup_month_2,pickup_month_3,...,dropoff_dayofweek_3,dropoff_dayofweek_4,dropoff_dayofweek_5,dropoff_dayofweek_6,dropoff_slot_Evening,dropoff_slot_Late_Night,dropoff_slot_Midnight,dropoff_slot_Morning,dropoff_slot_Night,dropoff_slot_Noon
0,1,1,-73.982155,40.767937,-73.964630,40.765602,NaN,455,0,1,...,0,0,0,0,1,0,0,0,0,0
1,0,1,-73.980415,40.738564,-73.999481,40.731152,NaN,663,0,0,...,0,0,0,1,0,1,0,0,0,0
2,1,1,-74.010040,40.719971,-74.012268,40.706718,NaN,429,0,0,...,0,0,0,0,0,0,0,0,1,0
3,1,1,-73.973053,40.793209,-73.972923,40.782520,NaN,435,0,1,...,0,0,1,0,0,0,0,0,0,1
4,1,6,-73.982857,40.742195,-73.992081,40.749184,NaN,443,0,0,...,0,0,1,0,0,0,1,0,0,0

In [28]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1066333 entries, 0 to 1066332
Data columns (total 43 columns):
 #   Column                   Non-Null Count    Dtype
---  ------                   --------------    -----
 0   vendor_id                1066333 non-null  int64
 1   passenger_count          1066333 non-null  int64
 2   pickup_longitude         1066333 non-null  float64
 3   pickup_latitude          1066333 non-null  float64
 4   dropoff_longitude        1066333 non-null  float64
 5   dropoff_latitude         1066333 non-null  float64
 6   store_and_fwd_flag       0 non-null        float64
 7   trip_duration            1066333 non-null  int64
 8   pickup_month_2           1066333 non-null  uint8
 9   pickup_month_3           1066333 non-null  uint8
 10  pickup_month_4           1066333 non-null  uint8
 11  pickup_month_5           1066333 non-null  uint8
 12  pickup_month_6           1066333 non-null  uint8
 13  pickup_dayofweek_1       1066333 non-null  uint8
 14  pickup_dayofweek_2       1066333 non-null  uint8
 15  pickup_dayofweek_3       1066333 non-null  uint8
 16  pickup_dayofweek_4       1066333 non-null  uint8
 17  pickup_dayofweek_5       1066333 non-null  uint8
 18  pickup_dayofweek_6       1066333 non-null  uint8
 19  pickup_slot_Evening      1066333 non-null  uint8
 20  pickup_slot_Late_Night   1066333 non-null  uint8
 21  pickup_slot_Midnight     1066333 non-null  uint8
 22  pickup_slot_Morning      1066333 non-null  uint8
 23  pickup_slot_Night        1066333 non-null  uint8
 24  pickup_slot_Noon         1066333 non-null  uint8
 25  dropoff_month_2          1066333 non-null  uint8
 26  dropoff_month_3          1066333 non-null  uint8
 27  dropoff_month_4          1066333 non-null  uint8
 28  dropoff_month_5          1066333 non-null  uint8
 29  dropoff_month_6          1066333 non-null  uint8
 30  dropoff_month_7          1066333 non-null  uint8
 31  dropoff_dayofweek_1      1066333 non-null  uint8
 32  dropoff_dayofweek_2      1066333 non-null  uint8
 33  dropoff_dayofweek_3      1066333 non-null  uint8
 34  dropoff_dayofweek_4      1066333 non-null  uint8
 35  dropoff_dayofweek_5      1066333 non-null  uint8
 36  dropoff_dayofweek_6      1066333 non-null  uint8
 37  dropoff_slot_Evening     1066333 non-null  uint8
 38  dropoff_slot_Late_Night  1066333 non-null  uint8
 39  dropoff_slot_Midnight    1066333 non-null  uint8
 40  dropoff_slot_Morning     1066333 non-null  uint8
 41  dropoff_slot_Night       1066333 non-null  uint8
 42  dropoff_slot_Noon        1066333 non-null  uint8
dtypes: float64(5), int64(3), uint8(35)
memory usage: 100.7 MB

In [27]:
df.to_csv('train_LR_prep.csv', index=False)