In [22]:
import numpy as np
import pandas as pd

import warnings

warnings.filterwarnings('ignore')

In [23]:
df = pd.read_csv('train_EDA.csv')
df.head()

,vendor_id,passenger_count,pickup_longitude,pickup_latitude,dropoff_longitude,dropoff_latitude,store_and_fwd_flag,trip_duration,pickup_month,pickup_dayofweek,pickup_slot,dropoff_month,dropoff_dayofweek,dropoff_hour,dropoff_slot
0,1,1,-73.982155,40.767937,-73.964630,40.765602,N,455,3,0,Evening,3,0,17,Evening
1,0,1,-73.980415,40.738564,-73.999481,40.731152,N,663,6,6,Late_Night,6,6,0,Late_Night
2,1,1,-74.010040,40.719971,-74.012268,40.706718,N,429,4,2,Night,4,2,19,Night
3,1,1,-73.973053,40.793209,-73.972923,40.782520,N,435,3,5,Noon,3,5,13,Noon
4,1,6,-73.982857,40.742195,-73.992081,40.749184,N,443,1,5,Midnight,1,5,22,Midnight

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1066333 entries, 0 to 1066332
Data columns (total 15 columns):
 #   Column              Non-Null Count    Dtype
---  ------              --------------    -----
 0   vendor_id           1066333 non-null  int64
 1   passenger_count     1066333 non-null  int64
 2   pickup_longitude    1066333 non-null  float64
 3   pickup_latitude     1066333 non-null  float64
 4   dropoff_longitude   1066333 non-null  float64
 5   dropoff_latitude    1066333 non-null  float64
 6   store_and_fwd_flag  1066333 non-null  object
 7   trip_duration       1066333 non-null  int64
 8   pickup_month        1066333 non-null  int64
 9   pickup_dayofweek    1066333 non-null  int64
 10  pickup_slot         1066333 non-null  object
 11  dropoff_month       1066333 non-null  int64
 12  dropoff_dayofweek   1066333 non-null  int64
 13  dropoff_hour        1066333 non-null  int64
 14  dropoff_slot        1066333 non-null  object
dtypes: float64(4), int64(8), object(3)
memory usage: 122.0+ MB

In [24]:
df = df.drop(['dropoff_month', 'dropoff_dayofweek', 'dropoff_hour', 'dropoff_slot'], axis=1)
df.head()

,vendor_id,passenger_count,pickup_longitude,pickup_latitude,dropoff_longitude,dropoff_latitude,store_and_fwd_flag,trip_duration,pickup_month,pickup_dayofweek,pickup_slot
0,1,1,-73.982155,40.767937,-73.964630,40.765602,N,455,3,0,Evening
1,0,1,-73.980415,40.738564,-73.999481,40.731152,N,663,6,6,Late_Night
2,1,1,-74.010040,40.719971,-74.012268,40.706718,N,429,4,2,Night
3,1,1,-73.973053,40.793209,-73.972923,40.782520,N,435,3,5,Noon
4,1,6,-73.982857,40.742195,-73.992081,40.749184,N,443,1,5,Midnight

In [25]:
df['store_and_fwd_flag'] = df['store_and_fwd_flag'].map({'Y':1, 'N':0})
df.head()

,vendor_id,passenger_count,pickup_longitude,pickup_latitude,dropoff_longitude,dropoff_latitude,store_and_fwd_flag,trip_duration,pickup_month,pickup_dayofweek,pickup_slot
0,1,1,-73.982155,40.767937,-73.964630,40.765602,0,455,3,0,Evening
1,0,1,-73.980415,40.738564,-73.999481,40.731152,0,663,6,6,Late_Night
2,1,1,-74.010040,40.719971,-74.012268,40.706718,0,429,4,2,Night
3,1,1,-73.973053,40.793209,-73.972923,40.782520,0,435,3,5,Noon
4,1,6,-73.982857,40.742195,-73.992081,40.749184,0,443,1,5,Midnight

In [26]:
d_pickup_month = pd.get_dummies(df['pickup_month'], prefix='pickup_month', drop_first=True)
d_pickup_month.head()

,pickup_month_2,pickup_month_3,pickup_month_4,pickup_month_5,pickup_month_6
0,0,1,0,0,0
1,0,0,0,0,1
2,0,0,1,0,0
3,0,1,0,0,0
4,0,0,0,0,0

In [27]:
df.isnull().sum()

vendor_id             0
passenger_count       0
pickup_longitude      0
pickup_latitude       0
dropoff_longitude     0
dropoff_latitude      0
store_and_fwd_flag    0
trip_duration         0
pickup_month          0
pickup_dayofweek      0
pickup_slot           0
dtype: int64

In [28]:
df = pd.concat([df, d_pickup_month], axis=1)
df = df.drop('pickup_month', axis=1)
df.head()

,vendor_id,passenger_count,pickup_longitude,pickup_latitude,dropoff_longitude,dropoff_latitude,store_and_fwd_flag,trip_duration,pickup_dayofweek,pickup_slot,pickup_month_2,pickup_month_3,pickup_month_4,pickup_month_5,pickup_month_6
0,1,1,-73.982155,40.767937,-73.964630,40.765602,0,455,0,Evening,0,1,0,0,0
1,0,1,-73.980415,40.738564,-73.999481,40.731152,0,663,6,Late_Night,0,0,0,0,1
2,1,1,-74.010040,40.719971,-74.012268,40.706718,0,429,2,Night,0,0,1,0,0
3,1,1,-73.973053,40.793209,-73.972923,40.782520,0,435,5,Noon,0,1,0,0,0
4,1,6,-73.982857,40.742195,-73.992081,40.749184,0,443,5,Midnight,0,0,0,0,0

In [29]:
d_pickup_dayofweek = pd.get_dummies(df['pickup_dayofweek'], prefix='pickup_dayofweek', drop_first=True)
d_pickup_dayofweek.head()

,pickup_dayofweek_1,pickup_dayofweek_2,pickup_dayofweek_3,pickup_dayofweek_4,pickup_dayofweek_5,pickup_dayofweek_6
0,0,0,0,0,0,0
1,0,0,0,0,0,1
2,0,1,0,0,0,0
3,0,0,0,0,1,0
4,0,0,0,0,1,0

In [30]:
df = pd.concat([df, d_pickup_dayofweek], axis=1)
df = df.drop('pickup_dayofweek', axis=1)
df.head()

,vendor_id,passenger_count,pickup_longitude,pickup_latitude,dropoff_longitude,dropoff_latitude,store_and_fwd_flag,trip_duration,pickup_slot,pickup_month_2,pickup_month_3,pickup_month_4,pickup_month_5,pickup_month_6,pickup_dayofweek_1,pickup_dayofweek_2,pickup_dayofweek_3,pickup_dayofweek_4,pickup_dayofweek_5,pickup_dayofweek_6
0,1,1,-73.982155,40.767937,-73.964630,40.765602,0,455,Evening,0,1,0,0,0,0,0,0,0,0,0
1,0,1,-73.980415,40.738564,-73.999481,40.731152,0,663,Late_Night,0,0,0,0,1,0,0,0,0,0,1
2,1,1,-74.010040,40.719971,-74.012268,40.706718,0,429,Night,0,0,1,0,0,0,1,0,0,0,0
3,1,1,-73.973053,40.793209,-73.972923,40.782520,0,435,Noon,0,1,0,0,0,0,0,0,0,1,0
4,1,6,-73.982857,40.742195,-73.992081,40.749184,0,443,Midnight,0,0,0,0,0,0,0,0,0,1,0

In [31]:
d_pickup_slot = pd.get_dummies(df['pickup_slot'], prefix='pickup_slot', drop_first=True)
d_pickup_slot.head()

,pickup_slot_Evening,pickup_slot_Late_Night,pickup_slot_Midnight,pickup_slot_Morning,pickup_slot_Night,pickup_slot_Noon
0,1,0,0,0,0,0
1,0,1,0,0,0,0
2,0,0,0,0,1,0
3,0,0,0,0,0,1
4,0,0,1,0,0,0

In [32]:
df = pd.concat([df, d_pickup_slot], axis=1)
df = df.drop('pickup_slot', axis=1)
df.head()

,vendor_id,passenger_count,pickup_longitude,pickup_latitude,dropoff_longitude,dropoff_latitude,store_and_fwd_flag,trip_duration,pickup_month_2,pickup_month_3,...,pickup_dayofweek_3,pickup_dayofweek_4,pickup_dayofweek_5,pickup_dayofweek_6,pickup_slot_Evening,pickup_slot_Late_Night,pickup_slot_Midnight,pickup_slot_Morning,pickup_slot_Night,pickup_slot_Noon
0,1,1,-73.982155,40.767937,-73.964630,40.765602,0,455,0,1,...,0,0,0,0,1,0,0,0,0,0
1,0,1,-73.980415,40.738564,-73.999481,40.731152,0,663,0,0,...,0,0,0,1,0,1,0,0,0,0
2,1,1,-74.010040,40.719971,-74.012268,40.706718,0,429,0,0,...,0,0,0,0,0,0,0,0,1,0
3,1,1,-73.973053,40.793209,-73.972923,40.782520,0,435,0,1,...,0,0,1,0,0,0,0,0,0,1
4,1,6,-73.982857,40.742195,-73.992081,40.749184,0,443,0,0,...,0,0,1,0,0,0,1,0,0,0

In [33]:
df.corr()

,vendor_id,passenger_count,pickup_longitude,pickup_latitude,dropoff_longitude,dropoff_latitude,store_and_fwd_flag,trip_duration,pickup_month_2,pickup_month_3,...,pickup_dayofweek_3,pickup_dayofweek_4,pickup_dayofweek_5,pickup_dayofweek_6,pickup_slot_Evening,pickup_slot_Late_Night,pickup_slot_Midnight,pickup_slot_Morning,pickup_slot_Night,pickup_slot_Noon
vendor_id,1.000000,0.294440,0.008223,0.007936,0.004944,0.006865,-0.072469,0.000857,0.003670,0.000789,...,-0.001958,-0.000529,0.000768,0.003181,0.003941,-0.008100,0.004436,0.006284,0.006360,-0.006067
passenger_count,0.294440,1.000000,-0.002686,-0.003527,-0.002321,-0.001482,-0.021212,0.008638,-0.000308,-0.001338,...,-0.008816,-0.000812,0.021174,0.017322,0.000745,0.011353,0.010116,-0.009354,0.005138,0.002443
pickup_longitude,0.008223,-0.002686,1.000000,0.147689,0.779473,0.096096,0.002006,-0.014507,-0.002217,-0.005131,...,0.000652,0.002562,-0.015212,-0.005431,0.006224,-0.030435,-0.015794,0.020010,-0.020204,0.012587
pickup_latitude,0.007936,-0.003527,0.147689,1.000000,0.103666,0.763546,-0.000619,-0.073000,-0.001487,-0.001863,...,0.010341,0.004386,-0.028836,-0.025439,0.038629,-0.115663,-0.050072,0.044780,-0.019100,0.052465
dropoff_longitude,0.004944,-0.002321,0.779473,0.103666,1.000000,0.160946,0.001780,0.020319,-0.003415,-0.003403,...,-0.001293,0.001879,-0.013609,0.002513,-0.005394,0.032654,0.000635,-0.015216,-0.014755,-0.008379
dropoff_latitude,0.006865,-0.001482,0.096096,0.763546,0.160946,1.000000,-0.000788,-0.062111,-0.003457,-0.000383,...,0.007805,0.001790,-0.024586,-0.016360,0.031317,-0.075539,-0.033864,0.019876,-0.010261,0.036876
store_and_fwd_flag,-0.072469,-0.021212,0.002006,-0.000619,0.001780,-0.000788,1.000000,0.004686,0.000821,-0.000863,...,0.001230,0.000441,-0.000368,-0.002309,0.003321,-0.001127,-0.000208,-0.000092,-0.001563,0.002549
trip_duration,0.000857,0.008638,-0.014507,-0.073000,0.020319,-0.062111,0.004686,1.000000,-0.010454,-0.001735,...,0.018310,0.011272,-0.004463,-0.031139,0.010023,-0.015468,0.009655,0.008666,0.004735,0.024718
pickup_month_2,0.003670,-0.000308,-0.002217,-0.001487,-0.003415,-0.003457,0.000821,-0.010454,1.000000,-0.209470,...,-0.003316,-0.005248,-0.000742,-0.003019,0.008211,-0.009606,-0.002649,0.003413,-0.003986,0.007931
pickup_month_3,0.000789,-0.001338,-0.005131,-0.001863,-0.003403,-0.000383,-0.000863,-0.001735,-0.209470,1.000000,...,0.020226,-0.017509,-0.011846,-0.016963,0.005401,-0.010604,-0.002665,-0.000706,0.004481,0.000954
pickup_month_4,-0.002456,0.001807,-0.000894,-0.000934,0.000770,0.001129,0.000131,0.006375,-0.204112,-0.210932,...,-0.018149,0.024220,0.038941,-0.007451,-0.003005,0.004035,0.003673,-0.001351,0.003965,-0.006068
pickup_month_5,-0.002490,-0.000761,0.001922,0.001943,0.003153,0.003705,-0.002496,0.007003,-0.200112,-0.206799,...,-0.018757,-0.021913,-0.014940,0.031643,-0.006079,0.006375,0.000804,-0.001076,-0.000155,-0.002066
pickup_month_6,-0.003538,-0.002671,0.002051,0.001993,0.001990,0.000274,0.000781,0.011978,-0.192767,-0.199208,...,0.029051,-0.014802,-0.010839,-0.014274,-0.014380,0.008208,0.008995,0.003157,0.000476,-0.010122
pickup_dayofweek_1,-0.000200,-0.010413,0.003686,0.014881,0.001774,0.012249,0.000068,0.008934,-0.011339,0.021274,...,-0.163053,-0.167619,-0.172045,-0.161365,0.008276,-0.070618,-0.000710,0.013078,0.020586,-0.005773
pickup_dayofweek_2,-0.000706,-0.009548,0.003748,0.013528,0.001515,0.010986,0.000119,0.013397,-0.007199,0.022122,...,-0.164847,-0.169464,-0.173937,-0.163141,-0.005434,-0.057477,0.007388,0.012946,0.020909,-0.010118
pickup_dayofweek_3,-0.001958,-0.008816,0.000652,0.010341,-0.001293,0.007805,0.001230,0.018310,-0.003316,0.020226,...,1.000000,-0.171919,-0.176458,-0.165505,-0.011088,-0.048152,0.017710,0.008672,0.016944,-0.011540
pickup_dayofweek_4,-0.000529,-0.000812,0.002562,0.004386,0.001879,0.001790,0.000441,0.011272,-0.005248,-0.017509,...,-0.171919,1.000000,-0.181400,-0.170140,-0.010938,-0.000447,0.020211,-0.002263,0.000612,-0.014408
pickup_dayofweek_5,0.000768,0.021174,-0.015212,-0.028836,-0.013609,-0.024586,-0.000368,-0.004463,-0.000742,-0.011846,...,-0.176458,-0.181400,1.000000,-0.174632,-0.003084,0.093378,0.011570,-0.021519,-0.029740,0.012861
pickup_dayofweek_6,0.003181,0.017322,-0.005431,-0.025439,0.002513,-0.016360,-0.002309,-0.031139,-0.003019,-0.016963,...,-0.165505,-0.170140,-0.174632,1.000000,0.000987,0.140739,-0.040780,-0.019428,-0.041964,0.022383
pickup_slot_Evening,0.003941,0.000745,0.006224,0.038629,-0.005394,0.031317,0.003321,0.010023,0.008211,0.005401,...,-0.011088,-0.010938,-0.003084,0.000987,1.000000,-0.150767,-0.144766,-0.200344,-0.202846,-0.204749
pickup_slot_Late_Night,-0.008100,0.011353,-0.030435,-0.115663,0.032654,-0.075539,-0.001127,-0.015468,-0.009606,-0.010604,...,-0.048152,-0.000447,0.093378,0.140739,-0.150767,1.000000,-0.120508,-0.166773,-0.168856,-0.170441
pickup_slot_Midnight,0.004436,0.010116,-0.015794,-0.050072,0.000635,-0.033864,-0.000208,0.009655,-0.002649,-0.002665,...,0.017710,0.020211,0.011570,-0.040780,-0.144766,-0.120508,1.000000,-0.160134,-0.162135,-0.163656
pickup_slot_Morning,0.006284,-0.009354,0.020010,0.044780,-0.015216,0.019876,-0.000092,0.008666,0.003413,-0.000706,...,0.008672,-0.002263,-0.021519,-0.019428,-0.200344,-0.166773,-0.160134,1.000000,-0.224381,-0.226486
pickup_slot_Night,0.006360,0.005138,-0.020204,-0.019100,-0.014755,-0.010261,-0.001563,0.004735,-0.003986,0.004481,...,0.016944,0.000612,-0.029740,-0.041964,-0.202846,-0.168856,-0.162135,-0.224381,1.000000,-0.229315
pickup_slot_Noon,-0.006067,0.002443,0.012587,0.052465,-0.008379,0.036876,0.002549,0.024718,0.007931,0.000954,...,-0.011540,-0.014408,0.012861,0.022383,-0.204749,-0.170441,-0.163656,-0.226486,-0.229315,1.000000

In [34]:
df.head()

,vendor_id,passenger_count,pickup_longitude,pickup_latitude,dropoff_longitude,dropoff_latitude,store_and_fwd_flag,trip_duration,pickup_month_2,pickup_month_3,...,pickup_dayofweek_3,pickup_dayofweek_4,pickup_dayofweek_5,pickup_dayofweek_6,pickup_slot_Evening,pickup_slot_Late_Night,pickup_slot_Midnight,pickup_slot_Morning,pickup_slot_Night,pickup_slot_Noon
0,1,1,-73.982155,40.767937,-73.964630,40.765602,0,455,0,1,...,0,0,0,0,1,0,0,0,0,0
1,0,1,-73.980415,40.738564,-73.999481,40.731152,0,663,0,0,...,0,0,0,1,0,1,0,0,0,0
2,1,1,-74.010040,40.719971,-74.012268,40.706718,0,429,0,0,...,0,0,0,0,0,0,0,0,1,0
3,1,1,-73.973053,40.793209,-73.972923,40.782520,0,435,0,1,...,0,0,1,0,0,0,0,0,0,1
4,1,6,-73.982857,40.742195,-73.992081,40.749184,0,443,0,0,...,0,0,1,0,0,0,1,0,0,0

In [37]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1066333 entries, 0 to 1066332
Data columns (total 25 columns):
 #   Column                  Non-Null Count    Dtype
---  ------                  --------------    -----
 0   vendor_id               1066333 non-null  int64
 1   passenger_count         1066333 non-null  int64
 2   pickup_longitude        1066333 non-null  float64
 3   pickup_latitude         1066333 non-null  float64
 4   dropoff_longitude       1066333 non-null  float64
 5   dropoff_latitude        1066333 non-null  float64
 6   store_and_fwd_flag      1066333 non-null  int64
 7   trip_duration           1066333 non-null  int64
 8   pickup_month_2          1066333 non-null  uint8
 9   pickup_month_3          1066333 non-null  uint8
 10  pickup_month_4          1066333 non-null  uint8
 11  pickup_month_5          1066333 non-null  uint8
 12  pickup_month_6          1066333 non-null  uint8
 13  pickup_dayofweek_1      1066333 non-null  uint8
 14  pickup_dayofweek_2      1066333 non-null  uint8
 15  pickup_dayofweek_3      1066333 non-null  uint8
 16  pickup_dayofweek_4      1066333 non-null  uint8
 17  pickup_dayofweek_5      1066333 non-null  uint8
 18  pickup_dayofweek_6      1066333 non-null  uint8
 19  pickup_slot_Evening     1066333 non-null  uint8
 20  pickup_slot_Late_Night  1066333 non-null  uint8
 21  pickup_slot_Midnight    1066333 non-null  uint8
 22  pickup_slot_Morning     1066333 non-null  uint8
 23  pickup_slot_Night       1066333 non-null  uint8
 24  pickup_slot_Noon        1066333 non-null  uint8
dtypes: float64(4), int64(4), uint8(17)
memory usage: 82.4 MB

In [44]:
from math import radians, cos, sin, asin, sqrt

In [59]:
def distance_fn(lat1, lat2, lon1, lon2):
    
    # The math module contains a function named
    # radians which converts from degrees to radians.
    lon1 = radians(lon1)
    lon2 = radians(lon2)
    lat1 = radians(lat1)
    lat2 = radians(lat2)
    
    # Haversine formula
    dlon = lon2 - lon1
    dlat = lat2 - lat1
    a = sin(dlat / 2)**2 + cos(lat1) * cos(lat2) * sin(dlon / 2)**2
 
    c = 2 * asin(sqrt(a))
    
    # Radius of earth in kilometers. Use 3956 for miles
    r = 6371
      
    # calculate the result
    return c * r

In [61]:
df['distance'] =  df.apply(lambda x: distance_fn(x['pickup_latitude'], x['dropoff_latitude'], x['pickup_longitude'], x['dropoff_longitude']), axis=1)

In [62]:
df.head()

,vendor_id,passenger_count,pickup_longitude,pickup_latitude,dropoff_longitude,dropoff_latitude,store_and_fwd_flag,trip_duration,pickup_month_2,pickup_month_3,...,pickup_dayofweek_4,pickup_dayofweek_5,pickup_dayofweek_6,pickup_slot_Evening,pickup_slot_Late_Night,pickup_slot_Midnight,pickup_slot_Morning,pickup_slot_Night,pickup_slot_Noon,distance
0,1,1,-73.982155,40.767937,-73.964630,40.765602,0,455,0,1,...,0,0,0,1,0,0,0,0,0,1.498521
1,0,1,-73.980415,40.738564,-73.999481,40.731152,0,663,0,0,...,0,0,1,0,1,0,0,0,0,1.805507
2,1,1,-74.010040,40.719971,-74.012268,40.706718,0,429,0,0,...,0,0,0,0,0,0,0,1,0,1.485498
3,1,1,-73.973053,40.793209,-73.972923,40.782520,0,435,0,1,...,0,1,0,0,0,0,0,0,1,1.188588
4,1,6,-73.982857,40.742195,-73.992081,40.749184,0,443,0,0,...,0,1,0,0,0,1,0,0,0,1.098942

In [63]:
df['distance'].describe()

count    1.066333e+06
mean     2.091746e+00
std      1.944522e+00
min      0.000000e+00
25%      1.105104e+00
50%      1.692154e+00
75%      2.600687e+00
max      8.912141e+02
Name: distance, dtype: float64

In [47]:
df.head()

,vendor_id,passenger_count,pickup_longitude,pickup_latitude,dropoff_longitude,dropoff_latitude,store_and_fwd_flag,trip_duration,pickup_month_2,pickup_month_3,...,pickup_dayofweek_3,pickup_dayofweek_4,pickup_dayofweek_5,pickup_dayofweek_6,pickup_slot_Evening,pickup_slot_Late_Night,pickup_slot_Midnight,pickup_slot_Morning,pickup_slot_Night,pickup_slot_Noon
0,1,1,-73.982155,40.767937,-73.964630,40.765602,0,455,0,1,...,0,0,0,0,1,0,0,0,0,0
1,0,1,-73.980415,40.738564,-73.999481,40.731152,0,663,0,0,...,0,0,0,1,0,1,0,0,0,0
2,1,1,-74.010040,40.719971,-74.012268,40.706718,0,429,0,0,...,0,0,0,0,0,0,0,0,1,0
3,1,1,-73.973053,40.793209,-73.972923,40.782520,0,435,0,1,...,0,0,1,0,0,0,0,0,0,1
4,1,6,-73.982857,40.742195,-73.992081,40.749184,0,443,0,0,...,0,0,1,0,0,0,1,0,0,0

In [64]:
df.to_csv('train_LR_prep.csv', index=False)