In [3]:
import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.feature_selection import RFE
from sklearn.linear_model import LinearRegression

import warnings
warnings.filterwarnings('ignore')

In [4]:
df = pd.read_csv('train_EDA.csv')
df.head()

,vendor_id,passenger_count,pickup_longitude,pickup_latitude,dropoff_longitude,dropoff_latitude,store_and_fwd_flag,trip_duration,pickup_month,pickup_dayofweek,pickup_hour,pickup_slot,dropoff_month,dropoff_dayofweek,dropoff_hour,dropoff_slot
0,1,1,-73.982155,40.767937,-73.964630,40.765602,N,455,3,0,17,Evening,3,0,17,Evening
1,0,1,-73.980415,40.738564,-73.999481,40.731152,N,663,6,6,0,Late_Night,6,6,0,Late_Night
2,1,1,-73.979027,40.763939,-74.005333,40.710087,N,2124,1,1,11,Morning,1,1,12,Noon
3,1,1,-74.010040,40.719971,-74.012268,40.706718,N,429,4,2,19,Night,4,2,19,Night
4,1,1,-73.973053,40.793209,-73.972923,40.782520,N,435,3,5,13,Noon,3,5,13,Noon

In [5]:
df['store_and_fwd_flag'] = df['store_and_fwd_flag'].map({'Y':1, 'N':0})
df.head()

,vendor_id,passenger_count,pickup_longitude,pickup_latitude,dropoff_longitude,dropoff_latitude,store_and_fwd_flag,trip_duration,pickup_month,pickup_dayofweek,pickup_hour,pickup_slot,dropoff_month,dropoff_dayofweek,dropoff_hour,dropoff_slot
0,1,1,-73.982155,40.767937,-73.964630,40.765602,0,455,3,0,17,Evening,3,0,17,Evening
1,0,1,-73.980415,40.738564,-73.999481,40.731152,0,663,6,6,0,Late_Night,6,6,0,Late_Night
2,1,1,-73.979027,40.763939,-74.005333,40.710087,0,2124,1,1,11,Morning,1,1,12,Noon
3,1,1,-74.010040,40.719971,-74.012268,40.706718,0,429,4,2,19,Night,4,2,19,Night
4,1,1,-73.973053,40.793209,-73.972923,40.782520,0,435,3,5,13,Noon,3,5,13,Noon

In [6]:
d_pickup_month = pd.get_dummies(df['pickup_month'], prefix='pickup_month', drop_first=True)
d_pickup_month.head()

,pickup_month_2,pickup_month_3,pickup_month_4,pickup_month_5,pickup_month_6
0,0,1,0,0,0
1,0,0,0,0,1
2,0,0,0,0,0
3,0,0,1,0,0
4,0,1,0,0,0

In [8]:
df = pd.concat([df, d_pickup_month], axis=1)
df = df.drop('pickup_month', axis=1)
df.head()

,vendor_id,passenger_count,pickup_longitude,pickup_latitude,dropoff_longitude,dropoff_latitude,store_and_fwd_flag,trip_duration,pickup_month,pickup_dayofweek,...,pickup_month_2,pickup_month_3,pickup_month_4,pickup_month_5,pickup_month_6,pickup_month_2,pickup_month_3,pickup_month_4,pickup_month_5,pickup_month_6
0,1,1,-73.982155,40.767937,-73.964630,40.765602,0,455,3,0,...,0,1,0,0,0,0,1,0,0,0
1,0,1,-73.980415,40.738564,-73.999481,40.731152,0,663,6,6,...,0,0,0,0,1,0,0,0,0,1
2,1,1,-73.979027,40.763939,-74.005333,40.710087,0,2124,1,1,...,0,0,0,0,0,0,0,0,0,0
3,1,1,-74.010040,40.719971,-74.012268,40.706718,0,429,4,2,...,0,0,1,0,0,0,0,1,0,0
4,1,1,-73.973053,40.793209,-73.972923,40.782520,0,435,3,5,...,0,1,0,0,0,0,1,0,0,0

In [9]:
df = df.loc[:, ~df.columns.duplicated()]
df.head()

,vendor_id,passenger_count,pickup_longitude,pickup_latitude,dropoff_longitude,dropoff_latitude,store_and_fwd_flag,trip_duration,pickup_month,pickup_dayofweek,...,pickup_slot,dropoff_month,dropoff_dayofweek,dropoff_hour,dropoff_slot,pickup_month_2,pickup_month_3,pickup_month_4,pickup_month_5,pickup_month_6
0,1,1,-73.982155,40.767937,-73.964630,40.765602,0,455,3,0,...,Evening,3,0,17,Evening,0,1,0,0,0
1,0,1,-73.980415,40.738564,-73.999481,40.731152,0,663,6,6,...,Late_Night,6,6,0,Late_Night,0,0,0,0,1
2,1,1,-73.979027,40.763939,-74.005333,40.710087,0,2124,1,1,...,Morning,1,1,12,Noon,0,0,0,0,0
3,1,1,-74.010040,40.719971,-74.012268,40.706718,0,429,4,2,...,Night,4,2,19,Night,0,0,1,0,0
4,1,1,-73.973053,40.793209,-73.972923,40.782520,0,435,3,5,...,Noon,3,5,13,Noon,0,1,0,0,0

In [13]:
d_pickup_dayofweek = pd.get_dummies(df['pickup_dayofweek'], prefix='pickup_dayofweek', drop_first=True)
d_pickup_dayofweek.head()

,pickup_dayofweek_1,pickup_dayofweek_2,pickup_dayofweek_3,pickup_dayofweek_4,pickup_dayofweek_5,pickup_dayofweek_6
0,0,0,0,0,0,0
1,0,0,0,0,0,1
2,1,0,0,0,0,0
3,0,1,0,0,0,0
4,0,0,0,0,1,0

In [14]:
df = pd.concat([df, d_pickup_dayofweek], axis=1)
df = df.drop('pickup_dayofweek', axis=1)
df.head()

,vendor_id,passenger_count,pickup_longitude,pickup_latitude,dropoff_longitude,dropoff_latitude,store_and_fwd_flag,trip_duration,pickup_hour,pickup_slot,...,pickup_month_3,pickup_month_4,pickup_month_5,pickup_month_6,pickup_dayofweek_1,pickup_dayofweek_2,pickup_dayofweek_3,pickup_dayofweek_4,pickup_dayofweek_5,pickup_dayofweek_6
0,1,1,-73.982155,40.767937,-73.964630,40.765602,0,455,17,Evening,...,1,0,0,0,0,0,0,0,0,0
1,0,1,-73.980415,40.738564,-73.999481,40.731152,0,663,0,Late_Night,...,0,0,0,1,0,0,0,0,0,1
2,1,1,-73.979027,40.763939,-74.005333,40.710087,0,2124,11,Morning,...,0,0,0,0,1,0,0,0,0,0
3,1,1,-74.010040,40.719971,-74.012268,40.706718,0,429,19,Night,...,0,1,0,0,0,1,0,0,0,0
4,1,1,-73.973053,40.793209,-73.972923,40.782520,0,435,13,Noon,...,1,0,0,0,0,0,0,0,1,0

In [15]:
d_pickup_slot = pd.get_dummies(df['pickup_slot'], prefix='pickup_slot', drop_first=True)
d_pickup_slot.head()

,pickup_slot_Evening,pickup_slot_Late_Night,pickup_slot_Midnight,pickup_slot_Morning,pickup_slot_Night,pickup_slot_Noon
0,1,0,0,0,0,0
1,0,1,0,0,0,0
2,0,0,0,1,0,0
3,0,0,0,0,1,0
4,0,0,0,0,0,1

In [16]:
df = pd.concat([df, d_pickup_slot], axis=1)
df = df.drop('pickup_slot', axis=1)
df.head()

,vendor_id,passenger_count,pickup_longitude,pickup_latitude,dropoff_longitude,dropoff_latitude,store_and_fwd_flag,trip_duration,pickup_hour,dropoff_month,...,pickup_dayofweek_3,pickup_dayofweek_4,pickup_dayofweek_5,pickup_dayofweek_6,pickup_slot_Evening,pickup_slot_Late_Night,pickup_slot_Midnight,pickup_slot_Morning,pickup_slot_Night,pickup_slot_Noon
0,1,1,-73.982155,40.767937,-73.964630,40.765602,0,455,17,3,...,0,0,0,0,1,0,0,0,0,0
1,0,1,-73.980415,40.738564,-73.999481,40.731152,0,663,0,6,...,0,0,0,1,0,1,0,0,0,0
2,1,1,-73.979027,40.763939,-74.005333,40.710087,0,2124,11,1,...,0,0,0,0,0,0,0,1,0,0
3,1,1,-74.010040,40.719971,-74.012268,40.706718,0,429,19,4,...,0,0,0,0,0,0,0,0,1,0
4,1,1,-73.973053,40.793209,-73.972923,40.782520,0,435,13,3,...,0,0,1,0,0,0,0,0,0,1

In [17]:
d_dropoff_month = pd.get_dummies(df['dropoff_month'], prefix='dropoff_month', drop_first=True)
d_dropoff_month.head()

,dropoff_month_2,dropoff_month_3,dropoff_month_4,dropoff_month_5,dropoff_month_6,dropoff_month_7
0,0,1,0,0,0,0
1,0,0,0,0,1,0
2,0,0,0,0,0,0
3,0,0,1,0,0,0
4,0,1,0,0,0,0

In [18]:
df = pd.concat([df, d_dropoff_month], axis=1)
df = df.drop('dropoff_month', axis=1)
df.head()

,vendor_id,passenger_count,pickup_longitude,pickup_latitude,dropoff_longitude,dropoff_latitude,store_and_fwd_flag,trip_duration,pickup_hour,dropoff_dayofweek,...,pickup_slot_Midnight,pickup_slot_Morning,pickup_slot_Night,pickup_slot_Noon,dropoff_month_2,dropoff_month_3,dropoff_month_4,dropoff_month_5,dropoff_month_6,dropoff_month_7
0,1,1,-73.982155,40.767937,-73.964630,40.765602,0,455,17,0,...,0,0,0,0,0,1,0,0,0,0
1,0,1,-73.980415,40.738564,-73.999481,40.731152,0,663,0,6,...,0,0,0,0,0,0,0,0,1,0
2,1,1,-73.979027,40.763939,-74.005333,40.710087,0,2124,11,1,...,0,1,0,0,0,0,0,0,0,0
3,1,1,-74.010040,40.719971,-74.012268,40.706718,0,429,19,2,...,0,0,1,0,0,0,1,0,0,0
4,1,1,-73.973053,40.793209,-73.972923,40.782520,0,435,13,5,...,0,0,0,1,0,1,0,0,0,0

In [19]:
d_dropoff_dayofweek = pd.get_dummies(df['dropoff_dayofweek'], prefix='dropoff_dayofweek', drop_first=True)
d_dropoff_dayofweek.head()

,dropoff_dayofweek_1,dropoff_dayofweek_2,dropoff_dayofweek_3,dropoff_dayofweek_4,dropoff_dayofweek_5,dropoff_dayofweek_6
0,0,0,0,0,0,0
1,0,0,0,0,0,1
2,1,0,0,0,0,0
3,0,1,0,0,0,0
4,0,0,0,0,1,0

In [20]:
df = pd.concat([df, d_dropoff_dayofweek], axis=1)
df = df.drop('dropoff_dayofweek', axis=1)
df.head()

,vendor_id,passenger_count,pickup_longitude,pickup_latitude,dropoff_longitude,dropoff_latitude,store_and_fwd_flag,trip_duration,pickup_hour,dropoff_hour,...,dropoff_month_4,dropoff_month_5,dropoff_month_6,dropoff_month_7,dropoff_dayofweek_1,dropoff_dayofweek_2,dropoff_dayofweek_3,dropoff_dayofweek_4,dropoff_dayofweek_5,dropoff_dayofweek_6
0,1,1,-73.982155,40.767937,-73.964630,40.765602,0,455,17,17,...,0,0,0,0,0,0,0,0,0,0
1,0,1,-73.980415,40.738564,-73.999481,40.731152,0,663,0,0,...,0,0,1,0,0,0,0,0,0,1
2,1,1,-73.979027,40.763939,-74.005333,40.710087,0,2124,11,12,...,0,0,0,0,1,0,0,0,0,0
3,1,1,-74.010040,40.719971,-74.012268,40.706718,0,429,19,19,...,1,0,0,0,0,1,0,0,0,0
4,1,1,-73.973053,40.793209,-73.972923,40.782520,0,435,13,13,...,0,0,0,0,0,0,0,0,1,0

In [21]:
d_dropoff_slot = pd.get_dummies(df['dropoff_slot'], prefix='dropoff_slot', drop_first=True)
d_dropoff_slot.head()

,dropoff_slot_Evening,dropoff_slot_Late_Night,dropoff_slot_Midnight,dropoff_slot_Morning,dropoff_slot_Night,dropoff_slot_Noon
0,1,0,0,0,0,0
1,0,1,0,0,0,0
2,0,0,0,0,0,1
3,0,0,0,0,1,0
4,0,0,0,0,0,1

In [22]:
df = pd.concat([df, d_dropoff_slot], axis=1)
df = df.drop('dropoff_slot', axis=1)
df.head()

,vendor_id,passenger_count,pickup_longitude,pickup_latitude,dropoff_longitude,dropoff_latitude,store_and_fwd_flag,trip_duration,pickup_hour,dropoff_hour,...,dropoff_dayofweek_3,dropoff_dayofweek_4,dropoff_dayofweek_5,dropoff_dayofweek_6,dropoff_slot_Evening,dropoff_slot_Late_Night,dropoff_slot_Midnight,dropoff_slot_Morning,dropoff_slot_Night,dropoff_slot_Noon
0,1,1,-73.982155,40.767937,-73.964630,40.765602,0,455,17,17,...,0,0,0,0,1,0,0,0,0,0
1,0,1,-73.980415,40.738564,-73.999481,40.731152,0,663,0,0,...,0,0,0,1,0,1,0,0,0,0
2,1,1,-73.979027,40.763939,-74.005333,40.710087,0,2124,11,12,...,0,0,0,0,0,0,0,0,0,1
3,1,1,-74.010040,40.719971,-74.012268,40.706718,0,429,19,19,...,0,0,0,0,0,0,0,0,1,0
4,1,1,-73.973053,40.793209,-73.972923,40.782520,0,435,13,13,...,0,0,1,0,0,0,0,0,0,1

In [23]:
df.corr()

,vendor_id,passenger_count,pickup_longitude,pickup_latitude,dropoff_longitude,dropoff_latitude,store_and_fwd_flag,trip_duration,pickup_hour,dropoff_hour,...,dropoff_dayofweek_3,dropoff_dayofweek_4,dropoff_dayofweek_5,dropoff_dayofweek_6,dropoff_slot_Evening,dropoff_slot_Late_Night,dropoff_slot_Midnight,dropoff_slot_Morning,dropoff_slot_Night,dropoff_slot_Noon
vendor_id,1.000000,0.287415,0.007820,0.001742,0.001528,0.004496,-0.079872,0.020304,0.009299,0.009250,...,-0.001663,-0.001568,0.000320,0.003171,0.003028,-0.004555,0.003263,0.005189,0.006424,-0.005031
passenger_count,0.287415,1.000000,0.002169,-0.005125,-0.000343,-0.002762,-0.021815,0.008471,0.009101,0.008449,...,-0.008558,-0.001059,0.020690,0.016182,0.000967,0.009285,0.008807,-0.010919,0.004026,0.003568
pickup_longitude,0.007820,0.002169,1.000000,0.022568,0.783582,0.100190,0.010799,0.026542,0.010150,0.010758,...,-0.000766,-0.002606,-0.017186,0.000307,0.013377,-0.020925,-0.003967,0.003977,-0.002050,0.004406
pickup_latitude,0.001742,-0.005125,0.022568,1.000000,0.114884,0.494038,-0.008223,-0.029204,0.010603,0.017043,...,0.009408,0.003884,-0.021352,-0.023573,0.022594,-0.089781,-0.044264,0.053353,-0.015519,0.041982
dropoff_longitude,0.001528,-0.000343,0.783582,0.114884,1.000000,0.124873,0.008226,0.014678,-0.022455,-0.023361,...,0.000587,0.001111,-0.008221,0.006201,-0.001046,0.019787,0.000034,-0.015425,-0.013387,-0.007126
dropoff_latitude,0.004496,-0.002762,0.100190,0.494038,0.124873,1.000000,-0.009818,-0.020677,0.013612,0.017246,...,0.003835,-0.000068,-0.017494,-0.012811,0.022803,-0.054037,-0.025746,0.021535,-0.008407,0.027961
store_and_fwd_flag,-0.079872,-0.021815,0.010799,-0.008223,0.008226,-0.009818,1.000000,0.001724,0.002245,0.002932,...,0.002677,0.001000,-0.003160,-0.003242,0.005998,-0.002840,-0.001423,-0.001582,-0.002727,0.004785
trip_duration,0.020304,0.008471,0.026542,-0.029204,0.014678,-0.020677,0.001724,1.000000,0.003690,0.002652,...,0.002323,0.002421,-0.004450,-0.001517,0.007825,0.001131,-0.002528,-0.001877,-0.003644,0.007281
pickup_hour,0.009299,0.009101,0.010150,0.010603,-0.022455,0.013612,0.002245,0.003690,1.000000,0.933977,...,0.028961,0.001514,-0.030820,-0.081204,0.218331,-0.555289,0.463645,-0.318020,0.448673,-0.026819
dropoff_hour,0.009250,0.008449,0.010758,0.017043,-0.023361,0.017246,0.002932,0.002652,0.933977,1.000000,...,0.031947,-0.000932,-0.037533,-0.088731,0.232406,-0.655928,0.470406,-0.296618,0.459671,-0.006814
pickup_month_2,0.002273,-0.001372,-0.005440,0.002229,-0.003873,-0.001243,-0.000308,-0.003262,0.004858,0.005001,...,-0.004826,-0.005847,0.001133,-0.000676,0.004866,-0.006358,-0.002310,0.001085,0.000780,0.003302
pickup_month_3,0.001183,-0.000900,-0.002102,0.001152,-0.000669,0.000744,-0.002311,-0.001950,0.005953,0.005963,...,0.020275,-0.018123,-0.011058,-0.015404,0.003360,-0.008687,-0.001234,0.001050,0.004370,-0.001863
pickup_month_4,-0.002483,0.001430,-0.001799,-0.001041,-0.000691,0.001071,0.000418,0.000296,0.002306,0.001699,...,-0.017925,0.026281,0.039253,-0.006957,-0.003913,0.002961,0.004773,-0.000219,0.002740,-0.002900
pickup_month_5,-0.002088,-0.000647,0.003606,-0.000517,0.003301,0.000574,-0.001071,0.003457,-0.003350,-0.003400,...,-0.016769,-0.020073,-0.015906,0.027054,-0.002126,0.002677,-0.000656,-0.001244,-0.002478,0.002357
pickup_month_6,-0.003400,-0.001666,0.004220,-0.001178,0.003136,-0.001746,0.002008,0.004500,-0.005274,-0.006063,...,0.030116,-0.013828,-0.013680,-0.014376,-0.008575,0.005672,0.006329,0.002664,-0.003703,-0.003100
pickup_dayofweek_1,0.001714,-0.008783,0.005036,0.013787,-0.001497,0.010962,-0.000167,0.001839,0.031394,0.035170,...,-0.168310,-0.170704,-0.169741,-0.158868,0.006114,-0.065960,-0.000429,0.024128,0.013201,0.001389
pickup_dayofweek_2,-0.001434,-0.009835,-0.001094,0.012912,-0.002486,0.009017,0.000923,0.001250,0.029280,0.031399,...,-0.160476,-0.174299,-0.173316,-0.162220,-0.003147,-0.054828,0.006399,0.021427,0.015192,-0.001892
pickup_dayofweek_3,-0.001472,-0.008440,-0.000826,0.009019,0.000726,0.003389,0.002295,0.003770,0.031162,0.028762,...,0.986576,-0.162864,-0.177362,-0.166007,-0.009730,-0.042549,0.017387,0.014903,0.013937,-0.006043
pickup_dayofweek_4,-0.001465,-0.000766,-0.002606,0.003659,0.001067,0.000284,0.001185,0.002496,0.002726,-0.002843,...,-0.178207,0.983306,-0.161630,-0.168216,-0.011668,0.004964,0.015605,0.002234,0.000386,-0.013792
pickup_dayofweek_5,0.000378,0.020799,-0.017653,-0.021456,-0.008743,-0.017658,-0.003103,-0.000923,-0.031157,-0.037287,...,-0.176951,-0.179463,0.981908,-0.148170,-0.004300,0.094181,0.011313,-0.042443,-0.017889,0.001685
pickup_dayofweek_6,0.002930,0.015675,0.001636,-0.022967,0.006563,-0.012253,-0.003384,-0.004344,-0.086868,-0.081483,...,-0.164734,-0.167077,-0.166134,0.985628,0.006408,0.120512,-0.037924,-0.038749,-0.034061,0.014838
pickup_slot_Evening,0.004461,0.001309,0.011273,0.023865,-0.004369,0.021419,0.004631,0.005445,0.237960,0.252519,...,-0.008224,-0.011086,-0.004582,0.001848,0.895060,-0.147632,-0.149268,-0.204363,-0.095038,-0.215374
pickup_slot_Late_Night,-0.005559,0.009060,-0.027147,-0.084237,0.018999,-0.050391,-0.003040,-0.003008,-0.637598,-0.619661,...,-0.048058,-0.000525,0.095192,0.132833,-0.140456,0.930793,-0.112197,-0.153762,-0.153015,-0.162151
pickup_slot_Midnight,0.002863,0.008632,-0.004259,-0.045649,0.001809,-0.027308,-0.001061,0.001183,0.469086,0.353871,...,0.012111,0.018982,0.017996,-0.027997,-0.145689,-0.008653,0.879554,-0.159504,-0.158430,-0.168207
pickup_slot_Morning,0.005755,-0.009549,0.001958,0.054528,-0.017392,0.019975,-0.001041,-0.001801,-0.304585,-0.282439,...,0.013471,0.000840,-0.037803,-0.035252,-0.204251,-0.161624,-0.163333,0.930181,-0.222510,-0.159237
pickup_slot_Night,0.005574,0.004124,-0.004723,-0.019225,-0.013870,-0.008242,-0.003565,-0.006313,0.462008,0.471692,...,0.016384,0.000248,-0.017567,-0.036926,-0.199458,-0.157896,-0.052364,-0.218455,0.905104,-0.230386
pickup_slot_Noon,-0.006003,0.003751,0.008345,0.036742,-0.002261,0.025546,0.005886,0.009101,-0.007925,0.012059,...,-0.005537,-0.012732,0.002397,0.014631,-0.126983,-0.169143,-0.171047,-0.234064,-0.233024,0.922973
dropoff_month_2,0.002252,-0.001410,-0.005417,0.002183,-0.003858,-0.001276,-0.000332,-0.005215,0.004822,0.005012,...,-0.004819,-0.005846,0.001139,-0.000670,0.004862,-0.006377,-0.002298,0.001087,0.000777,0.003305
dropoff_month_3,0.001237,-0.000887,-0.002103,0.001196,-0.000716,0.000780,-0.002279,-0.000099,0.005818,0.006172,...,0.020317,-0.018644,-0.011018,-0.015366,0.003407,-0.008968,-0.001201,0.001082,0.004430,-0.001824
dropoff_month_4,-0.002487,0.001428,-0.001784,-0.001024,-0.000646,0.001097,0.000395,0.000324,0.002289,0.001745,...,-0.017919,0.026858,0.039260,-0.007598,-0.003901,0.002884,0.004766,-0.000193,0.002753,-0.002888
dropoff_month_5,-0.002111,-0.000636,0.003578,-0.000524,0.003309,0.000542,-0.001080,0.003554,-0.003183,-0.003654,...,-0.016820,-0.020123,-0.015956,0.027652,-0.002174,0.003047,-0.000693,-0.001307,-0.002540,0.002300
dropoff_month_6,-0.003371,-0.001653,0.004223,-0.001154,0.003122,-0.001675,0.002044,0.004396,-0.005466,-0.005789,...,0.030177,-0.014431,-0.013624,-0.014324,-0.008523,0.005278,0.006370,0.002739,-0.003639,-0.003043
dropoff_month_7,-0.000286,-0.000749,0.001528,-0.003229,0.000984,-0.003590,-0.000695,0.015188,0.012342,-0.017793,...,-0.003909,0.021964,-0.003942,-0.003690,-0.003809,0.025001,-0.002730,-0.004392,-0.003988,-0.003893
dropoff_dayofweek_1,0.001459,-0.008866,0.005359,0.013720,-0.001398,0.011023,-0.000187,-0.001009,0.030934,0.035886,...,-0.168199,-0.170591,-0.169629,-0.158769,0.006347,-0.066986,-0.000368,0.024299,0.013381,0.001507
dropoff_dayofweek_2,-0.001231,-0.009797,-0.000971,0.013047,-0.002631,0.009294,0.000789,0.002556,0.028273,0.032955,...,-0.171689,-0.174132,-0.173150,-0.162064,-0.002831,-0.056966,0.006643,0.021709,0.015585,-0.001504
dropoff_dayofweek_3,-0.001663,-0.008558,-0.000766,0.009408,0.000587,0.003835,0.002677,0.002323,0.028961,0.031947,...,1.000000,-0.177971,-0.176967,-0.165637,-0.009007,-0.047023,0.017955,0.015656,0.014550,-0.005319
dropoff_dayofweek_4,-0.001568,-0.001059,-0.002606,0.003884,0.001111,-0.000068,0.001000,0.002421,0.001514,-0.000932,...,-0.177971,1.000000,-0.179484,-0.167993,-0.011289,0.002228,0.015880,0.002740,0.000859,-0.013373
dropoff_dayofweek_5,0.000320,0.020690,-0.017186,-0.021352,-0.008221,-0.017494,-0.003160,-0.004450,-0.030820,-0.037533,...,-0.176967,-0.179484,1.000000,-0.167046,-0.004439,0.094460,0.011289,-0.042446,-0.017929,0.001638
dropoff_dayofweek_6,0.003171,0.016182,0.000307,-0.023573,0.006201,-0.012811,-0.003242,-0.001517,-0.081204,-0.088731,...,-0.165637,-0.167993,-0.167046,1.000000,0.004808,0.130678,-0.038962,-0.040322,-0.035638,0.012995
dropoff_slot_Evening,0.003028,0.000967,0.013377,0.022594,-0.001046,0.022803,0.005998,0.007825,0.218331,0.232406,...,-0.009007,-0.011289,-0.004439,0.004808,1.000000,-0.146357,-0.147787,-0.202328,-0.201337,-0.213374
dropoff_slot_Late_Night,-0.004555,0.009285,-0.020925,-0.089781,0.019787,-0.054037,-0.002840,0.001131,-0.555289,-0.655928,...,-0.047023,0.002228,0.094460,0.130678,-0.146357,1.000000,-0.117036,-0.160228,-0.159443,-0.168976
dropoff_slot_Midnight,0.003263,0.008807,-0.003967,-0.044264,0.000034,-0.025746,-0.001423,-0.002528,0.463645,0.470406,...,0.017955,0.015880,0.011289,-0.038962,-0.147787,-0.117036,1.000000,-0.161794,-0.161002,-0.170628
dropoff_slot_Morning,0.005189,-0.010919,0.003977,0.053353,-0.015425,0.021535,-0.001582,-0.001877,-0.318020,-0.296618,...,0.015656,0.002740,-0.042446,-0.040322,-0.202328,-0.160228,-0.161794,1.000000,-0.220419,-0.233597
dropoff_slot_Night,0.006424,0.004026,-0.002050,-0.015519,-0.013387,-0.008407,-0.002727,-0.003644,0.448673,0.459671,...,0.014550,0.000859,-0.017929,-0.035638,-0.201337,-0.159443,-0.161002,-0.220419,1.000000,-0.232453
dropoff_slot_Noon,-0.005031,0.003568,0.004406,0.041982,-0.007126,0.027961,0.004785,0.007281,-0.026819,-0.006814,...,-0.005319,-0.013373,0.001638,0.012995,-0.213374,-0.168976,-0.170628,-0.233597,-0.232453,1.000000

In [24]:
import statsmodels.api as sm

In [25]:
y_train = df.pop('trip_duration')
X_train = df

In [26]:
X_train.head()

,vendor_id,passenger_count,pickup_longitude,pickup_latitude,dropoff_longitude,dropoff_latitude,store_and_fwd_flag,pickup_hour,dropoff_hour,pickup_month_2,...,dropoff_dayofweek_3,dropoff_dayofweek_4,dropoff_dayofweek_5,dropoff_dayofweek_6,dropoff_slot_Evening,dropoff_slot_Late_Night,dropoff_slot_Midnight,dropoff_slot_Morning,dropoff_slot_Night,dropoff_slot_Noon
0,1,1,-73.982155,40.767937,-73.964630,40.765602,0,17,17,0,...,0,0,0,0,1,0,0,0,0,0
1,0,1,-73.980415,40.738564,-73.999481,40.731152,0,0,0,0,...,0,0,0,1,0,1,0,0,0,0
2,1,1,-73.979027,40.763939,-74.005333,40.710087,0,11,12,0,...,0,0,0,0,0,0,0,0,0,1
3,1,1,-74.010040,40.719971,-74.012268,40.706718,0,19,19,0,...,0,0,0,0,0,0,0,0,1,0
4,1,1,-73.973053,40.793209,-73.972923,40.782520,0,13,13,0,...,0,0,1,0,0,0,0,0,0,1

In [28]:
df.head()

,vendor_id,passenger_count,pickup_longitude,pickup_latitude,dropoff_longitude,dropoff_latitude,store_and_fwd_flag,pickup_hour,dropoff_hour,pickup_month_2,...,dropoff_dayofweek_3,dropoff_dayofweek_4,dropoff_dayofweek_5,dropoff_dayofweek_6,dropoff_slot_Evening,dropoff_slot_Late_Night,dropoff_slot_Midnight,dropoff_slot_Morning,dropoff_slot_Night,dropoff_slot_Noon
0,1,1,-73.982155,40.767937,-73.964630,40.765602,0,17,17,0,...,0,0,0,0,1,0,0,0,0,0
1,0,1,-73.980415,40.738564,-73.999481,40.731152,0,0,0,0,...,0,0,0,1,0,1,0,0,0,0
2,1,1,-73.979027,40.763939,-74.005333,40.710087,0,11,12,0,...,0,0,0,0,0,0,0,0,0,1
3,1,1,-74.010040,40.719971,-74.012268,40.706718,0,19,19,0,...,0,0,0,0,0,0,0,0,1,0
4,1,1,-73.973053,40.793209,-73.972923,40.782520,0,13,13,0,...,0,0,1,0,0,0,0,0,0,1

In [29]:
df = pd.concat([X_train, y_train], axis=1)
df.head()

,vendor_id,passenger_count,pickup_longitude,pickup_latitude,dropoff_longitude,dropoff_latitude,store_and_fwd_flag,pickup_hour,dropoff_hour,pickup_month_2,...,dropoff_dayofweek_4,dropoff_dayofweek_5,dropoff_dayofweek_6,dropoff_slot_Evening,dropoff_slot_Late_Night,dropoff_slot_Midnight,dropoff_slot_Morning,dropoff_slot_Night,dropoff_slot_Noon,trip_duration
0,1,1,-73.982155,40.767937,-73.964630,40.765602,0,17,17,0,...,0,0,0,1,0,0,0,0,0,455
1,0,1,-73.980415,40.738564,-73.999481,40.731152,0,0,0,0,...,0,0,1,0,1,0,0,0,0,663
2,1,1,-73.979027,40.763939,-74.005333,40.710087,0,11,12,0,...,0,0,0,0,0,0,0,0,1,2124
3,1,1,-74.010040,40.719971,-74.012268,40.706718,0,19,19,0,...,0,0,0,0,0,0,0,1,0,429
4,1,1,-73.973053,40.793209,-73.972923,40.782520,0,13,13,0,...,0,1,0,0,0,0,0,0,1,435

In [30]:
df.to_csv('train_LR_prep.csv', index=False)